### Variables
@baseUrl = {{apiUrl}}/chat
@contentType = application/json

### Frage nach dem Wetter auf dem Sea You Festival
POST {{baseUrl}}/message
Content-Type: {{contentType}}

{
  "userId": "123e4567-e89b-12d3-a456-426614174000",
  "message": "Welche Festivals finden 2024 in 100 km Umkreis von Ingolstadt statt?"
}

### Frage nach anstehenden Festivals mit den besten Wetteraussichten im Raum Hamburg
POST {{baseUrl}}/message
Content-Type: {{contentType}}

{
  "userId": "456e7890-e89b-12d3-a456-426614174002",
  "message": "Ich suche nach einem Festival in Stuttgart. Hast du Empfehlungen für diese Woche?"
}

### Frage nach dem üblichen Wetter auf dem großen Rock-Festival in Österreich
POST {{baseUrl}}/message
Content-Type: {{contentType}}

{
  "userId": "789e0123-e89b-12d3-a456-426614174004",
  "message": "Welches große Rock-Festival findet jährlich in Österreich statt? Wie ist das Wetter dort üblicherweise?"
}

### Frage nach dem Wetter auf dem Deichbrand Festival
POST {{baseUrl}}/message
Content-Type: {{contentType}}

{
  "userId": "789e0123-e89b-12d3-a456-426614174004",
  "message": "Wie wird das Wetter auf dem Deichbrand Festival?"
}
