server:
  port: ${PORT:8080}
spring:
  application.name: "festivalgpt"
  main.banner-mode: "off"
  output.ansi.enabled: always
  security:
    user:
      name: user
      password: disabled
  datasource:
    url: "jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:${spring.application.name}}?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: "org.hibernate.dialect.MariaDBDialect"
    hibernate.ddl-auto: update
    show-sql: false
    open-in-view: false
  ai:
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        api-key: ${QDRANT_API_KEY:}
        collection-name: ${QDRANT_COLLECTION_NAME:${spring.application.name}}
logging:
  level:
    root: info
    org.springframework: info
    de.festivalgpt: ${LOG_LEVEL:info}
anthropic:
  api:
    key: ${ANTHROPIC_API_KEY}
    model: ${ANTHROPIC_MODEL}
